name: aaronlam1004 Vue Website Build

on:
  push:
    branches:
      - master

jobs: 
  build:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
      - uses: actions/checkout@v3
      - id: Build-Vue
        uses: xRealNeon/VuePagesAction@1.0.1
        with:
          username: 'aaronlam1004'
          reponame: 'aaronlam1004.github.io'
          token: ${{ secrets.GITHUB_TOKEN }}

